name: Chocolate Doom

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest]

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libpng-dev libsamplerate0-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev ninja-build

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: CMake
        env:
          CC: ${{ matrix.compiler }}
        run: cmake -S . -B build -G Ninja && ninja -C build

      - name: Make
        env:
          CC: ${{ matrix.compiler }}
        run: $GITHUB_WORKSPACE/.travis.sh

  cppcheck:
    runs-on: ubuntu-18.04

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cppcheck

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run cppcheck
        env:
          ANALYZE: true
        run: $GITHUB_WORKSPACE/.travis.sh

  crossbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64-x86-64

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cross build
        env:
          CROSSRULE: "--host=x86_64-w64-mingw32"
        run: $GITHUB_WORKSPACE/.travis.sh
